# Generated by Django 5.1 on 2024-09-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(blank=True, max_length=255, verbose_name="Avatar"),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(
                blank=True, max_length=255, verbose_name="Website URL"
            ),
        ),
    ]
