# Generated by Django 5.1 on 2024-09-05 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_description_user_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(editable=False, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(editable=False, verbose_name="Updated"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        related_query_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "followed",
                    models.ForeignKey(
                        help_text="The user being followed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Followed",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        help_text="The user who is following another user.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Follower",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        related_query_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Followers",
                "permissions": [
                    ("create_follow", "Create follow"),
                    ("list_follow", "List follow"),
                    ("view_follow", "View follow"),
                    ("change_follow", "Change follow"),
                ],
                "abstract": False,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("follower", "followed"),
                        name="users_follow_unique_follow_check",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("follower", models.F("followed")), _negated=True
                        ),
                        name="users_follow_prevent_self_follow_check",
                    ),
                ],
            },
        ),
    ]
