# Generated by Django 5.1 on 2024-09-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_by",
        ),
    ]
